docker-build:
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_IMAGE_NAME: davieduardocosta001/fast_zero:latest

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

  script:
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - docker run "$DOCKER_IMAGE_NAME" poetry run task test
    - docker push "$DOCKER_IMAGE_NAME"
